apiVersion: v1
data:
  olmCAKey: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQVdLZ0F3SUJBZ0lJYjZMYVNEWTNRNmd3Q2dZSUtvWkl6ajBFQXdJd1FqRVdNQlFHQTFVRUNoTU4KVW1Wa0lFaGhkQ3dnU1c1akxqRW9NQ1lHQTFVRUF4TWZiMnh0TFhObGJHWnphV2R1WldRdE5tWmhNbVJoTkRnegpOak0zTkROaE9EQWVGdzB5TlRBeU1UVXlNREkzTlRkYUZ3MHlOekF5TVRVeU1ESTNOVGRhTUVJeEZqQVVCZ05WCkJBb1REVkpsWkNCSVlYUXNJRWx1WXk0eEtEQW1CZ05WQkFNVEgyOXNiUzF6Wld4bWMybG5ibVZrTFRabVlUSmsKWVRRNE16WXpOelF6WVRnd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTTWhRWkNwMmxFZW5BVgpXOGl3dHhyZXdSeTZ3UzNpaEJnTFpjYjlNcXJWaUl3L21YTDBUNzBadjFUcWlVcXZpVFJvTHcvNDlncktBbmtMCmJVS0VYdm1SbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVldlo1TWdsbFdUWnpRa2M3Uzh1aXd4aW05bll3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU9xUwpDU3crM3piOHNvdWZFN3VKcG9ZTmxodHBjeDQyOWNvRHNjbDFzTDVqQWlFQXF0WWVtZ21TSUw2NlRSK09CZmpiCmRFTU15cFdRWGVLano5WDQ4RndkdHVZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNiRENDQWhPZ0F3SUJBZ0lJRXY0Mk1MWGIxdXd3Q2dZSUtvWkl6ajBFQXdJd1FqRVdNQlFHQTFVRUNoTU4KVW1Wa0lFaGhkQ3dnU1c1akxqRW9NQ1lHQTFVRUF4TWZiMnh0TFhObGJHWnphV2R1WldRdE5tWmhNbVJoTkRnegpOak0zTkROaE9EQWVGdzB5TlRBeU1UVXlNREkzTlRkYUZ3MHlOekF5TVRVeU1ESTNOVGRhTUVzeEZqQVVCZ05WCkJBb1REVkpsWkNCSVlYUXNJRWx1WXk0eE1UQXZCZ05WQkFNVEtIWndZUzFoWkcxcGMzTnBiMjR0WTI5dWRISnYKYkd4bGNpMXpaWEoyYVdObExtUmxabUYxYkhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRRwp0eEZFOWVIeXk3dTJvWTIreVErV0U1VkRwZGs5ekhnc2hNaFdCTmJ4aEVrZzhPc3V6OXo4eDVJaGQxVjA4N0tSCjdwZFlzTWJLUXNad1NyT1lreXZNbzRIcE1JSG1NQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWQKRXdFQi93UUNNQUF3SHdZRFZSMGpCQmd3Rm9BVWV2WjVNZ2xsV1RaelFrYzdTOHVpd3hpbTluWXdnWjhHQTFVZApFUVNCbHpDQmxJSW9kbkJoTFdGa2JXbHpjMmx2YmkxamIyNTBjbTlzYkdWeUxYTmxjblpwWTJVdVpHVm1ZWFZzCmRJSXNkbkJoTFdGa2JXbHpjMmx2YmkxamIyNTBjbTlzYkdWeUxYTmxjblpwWTJVdVpHVm1ZWFZzZEM1emRtT0MKT25ad1lTMWhaRzFwYzNOcGIyNHRZMjl1ZEhKdmJHeGxjaTF6WlhKMmFXTmxMbVJsWm1GMWJIUXVjM1pqTG1OcwpkWE4wWlhJdWJHOWpZV3d3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVUVRTXpycjhTZzFyQ0RDOE9lZlBHcTIvCjJNY0pVdi94SEVjcnhGeSt1aUVDSUdmYk02a2kyckF3RUw3Y04rU0FJMGJmeFJFUHFWa3YvN29xNzBxeDh6WmMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUY0T2t4TStCTG5NSUVCK28ySEwxeXhCNDVHL0hHNnBEQVNEd2o5WTJqQmpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQnJjUlJQWGg4c3U3dHFHTnZza1BsaE9WUTZYWlBjeDRMSVRJVmdUVzhZUkpJUERyTHMvYwovTWVTSVhkVmRQT3lrZTZYV0xER3lrTEdjRXF6bUpNcnpBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  annotations:
    olmcahash: b6f984fb570ccf0c32ade5cbcdee91a4540f064f909d8db184453af6b5e87d30
  creationTimestamp: "2025-02-15T20:27:57Z"
  labels:
    olm.managed: "true"
    operators.coreos.com/emr-dynamic-sizing.default: ""
  name: vpa-admission-controller-service-cert
  namespace: default
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: emr-dynamic-sizing.v0.0.2
    uid: 61062d54-efff-49c0-995d-496d8593d54f
  resourceVersion: "5665"
  uid: fba7eb3d-580c-46c6-9df5-e155297bde6f
type: kubernetes.io/tls
