apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2023-12-10T20:21:31Z"
    name: default
    namespace: grafana
    resourceVersion: "248001"
    uid: 9fab6638-88fe-4f0a-81a1-85236334e98d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: grafana
      meta.helm.sh/release-namespace: grafana
    creationTimestamp: "2023-12-10T20:23:37Z"
    labels:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 10.2.2
      helm.sh/chart: grafana-7.0.11
    name: grafana
    namespace: grafana
    resourceVersion: "248479"
    uid: ad29a6ae-1abe-4bc6-9286-fe70475b5b38
kind: List
metadata:
  resourceVersion: ""
